"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET', None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'social_django',
    'varpauth',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', None),
        'USER': os.environ.get('POSTGRES_USER', None),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', None),
        'HOST': os.environ.get('DB_HOST', None),
        'PORT': os.environ.get('DB_PORT', None),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'varpauth.backend.CustomOAuth2',
)

OAUTH_SERVER_NAME = 'varpauth'

SOCIAL_AUTH_PIPELINE = [ 
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'social_core.pipeline.social_auth.associate_by_email',
]

# OAUTH_SERVER_BASEURL = 'auth.localhost.com'
# SOCIAL_AUTH_VARPAUTH_KEY = 'j3JaoASDmwB6pvVbQRqIHKQrYqmkhiAvNYOjwtCE'
# SOCIAL_AUTH_VARPAUTH_SECRET = 'LbSPjabO7ZDJ2joeCkxEjT5scfVzw2REI8LZNYbcnnUfYpICfYJE8lnuUfyNCQFsgi09Ch6sKzASLmrjNKwEqMo0K2Cd8KAJZ6kbYDHy8hdVdMpUXBbVmS9YjkQfnYNR'

# OAUTH_SERVER_BASEURL='auth.ei.team'
# SOCIAL_AUTH_CUSTOM_KEY='FZTda7iyCCH8vtkaXG0Za6oo2YRxc0JSvKUvpl3N'
# SOCIAL_AUTH_CUSTOM_SECRET='eEC5Q8e6zzIWnHJEbD3dmWGrIGimWUowxrHhMmTJX1HgMDk2kvVWonc8gJFrHWhtq4LcQObOZbXbwtdbklWW31Vqri4UggvH4HIb6FQ0MBYVQfuEgGyAqd2h7HGAMjpE'

OAUTH_SERVER_BASEURL = 'auth.dev.itrashyou.com'
SOCIAL_AUTH_VARPAUTH_KEY = 'mZBepKZObDaAF02pH8axjLS3CsX0GKT8fpgPRQcd'
SOCIAL_AUTH_VARPAUTH_SECRET = '6H6LGrRqqyVzmJTRmgUva4YvM04n1kNZP37gh3upBwVFxS08MF2WNLjwVA0dtQJZZs5oIUq1EqjSYFnSVt3cxzelsxpw7aF7X8w72rs67bNPG97BpEHPOhr31HO3Hmk1'

LOGIN_REDIRECT_URL='app:home'

SOCIAL_AUTH_REDIRECT_IS_HTTPS=False